### ISSUE TITLE
Whitelisting only /

### ISSUE THREAD

**Issue by gnclmorais** [benbalter/jekyll-auth#80]
Does anyone know how to whitelist only `/`, the homepage? I’ve tried a couple of things, but I’m yet to make it work…

**Comment by parkr** [comment]
Did you try:

```yaml
jekyll_auth:
  whitelist:
    - "^$"
```
