### ISSUE TITLE
Custom webrick headers in _config.yml

### ISSUE THREAD

**Issue by jwarren116** [benbalter/jekyll-auth#83]
I'm trying to set custom webrick headers in my `_config.yml` file. It works using `jekyll serve`, but not using `jekyll-auth serve`. The block from `_config.yml` is below. If there is another work-around, let me know. I'm following all the basic setup and configuration, nothing extra or fancy.

``` yaml
webrick:
  headers:
    X-Frame-Options: ALLOW-FROM https://example.com/
```

Any assistance would be appreciated!
